package com.announcements.AutomateAnnouncements.services;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import com.announcements.AutomateAnnouncements.dtos.response.AssetResponseDTO;
import com.announcements.AutomateAnnouncements.dtos.response.PostDraftResponseDTO;
import com.announcements.AutomateAnnouncements.dtos.response.UserPostResponseDTO;
import com.announcements.AutomateAnnouncements.dtos.request.UserPostRequestDTO;
import com.announcements.AutomateAnnouncements.integration.BlobStorageService;
import com.announcements.AutomateAnnouncements.integration.BlotatoVideoService;
import com.announcements.AutomateAnnouncements.integration.N8nIntegrationService;
import com.announcements.AutomateAnnouncements.repositories.UserProfileRepository;
import com.announcements.AutomateAnnouncements.entities.UserProfile;

import java.io.File;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

@Slf4j
@Service
public class VideoService {

    @Autowired
    private AssetService assetService;

    @Autowired
    private PostDraftService postDraftService;

    @Autowired
    private UserPostService userPostService;

    @Autowired
    private UserProfileRepository userProfileRepository;

    @Autowired
    private BlobStorageService blobStorageService;

    @Autowired
    private N8nIntegrationService n8nIntegrationService;

    @Autowired
    private BlotatoVideoService blotatoVideoService;

    @Transactional
    public String uploadUserVideo(MultipartFile file, String title, String description, String authUserId, String targets) {
        log.info("Starting video upload process for authUserId: {}, targets: {}", authUserId, targets);

        // Get user profile by authUserId
        UserProfile userProfile = userProfileRepository.findByAuthUserId(authUserId)
                .orElseThrow(() -> new RuntimeException("User profile not found for authUserId: " + authUserId));
        Integer ownerId = userProfile.getId();

        // Upload file to blob storage
        String videoUrl = blobStorageService.uploadFile(file);
        log.info("Video uploaded to blob storage: {}", videoUrl);

        // Create asset record
        com.announcements.AutomateAnnouncements.dtos.request.AssetRequestDTO assetRequest = new com.announcements.AutomateAnnouncements.dtos.request.AssetRequestDTO();
        assetRequest.setOwner(ownerId);
        assetRequest.setType("video");
        assetRequest.setSource(file.getOriginalFilename());
        assetRequest.setBlobUrl(videoUrl);
        AssetResponseDTO asset = assetService.create(assetRequest);
        log.info("Asset created with ID: {}", asset.getId());

        // Create post draft (legacy)
        com.announcements.AutomateAnnouncements.dtos.request.PostDraftRequestDTO postDraftRequest = new com.announcements.AutomateAnnouncements.dtos.request.PostDraftRequestDTO();
        postDraftRequest.setTitle(title);
        postDraftRequest.setDescription(description);
        postDraftRequest.setAssetId(asset.getId());
        postDraftRequest.setTargets(targets);
        postDraftRequest.setStatus("pending");
        PostDraftResponseDTO postDraft = postDraftService.create(postDraftRequest);
        log.info("Post draft created with ID: {}", postDraft.getId());

        // Create UserPost (new system)
        UserPostRequestDTO userPostRequest = new UserPostRequestDTO();
        userPostRequest.setTitle(title);
        userPostRequest.setContent(description);
        userPostRequest.setVideoUrl(videoUrl);
        userPostRequest.setStatus("published"); // Auto-publish when video is uploaded

        // Parse targets into list
        List<String> targetList = Arrays.stream(targets.split(","))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .collect(Collectors.toList());
        userPostRequest.setTargetPlatforms(targetList);

        UserPostResponseDTO userPost = userPostService.createPost(authUserId, userPostRequest);
        log.info("UserPost created with ID: {}", userPost.getId());

        // Send to n8n
        n8nIntegrationService.sendVideoToN8n(title, description, videoUrl, postDraft.getTargets());
        log.info("Video data sent to n8n successfully");

        return videoUrl;
    }

    @Transactional
    public String generateVideoFromPrompt(String prompt, String title, String description, Integer ownerId, String targets, String style) {
        log.info("Starting video generation process for user: {}, targets: {}", ownerId, targets);

        // Generate video with Blotato API
        String styleToUse = style != null ? style : "default";
        String blotatoVideoUrl = blotatoVideoService.generateVideo(prompt, styleToUse);
        log.info("Video generated by Blotato API with style '{}': {}", styleToUse, blotatoVideoUrl);

        // The video is already hosted by Blotato, so we use their URL directly
        String videoUrl = blotatoVideoUrl;
        log.info("Using Blotato video URL directly: {}", videoUrl);

        // Create asset record
        com.announcements.AutomateAnnouncements.dtos.request.AssetRequestDTO assetRequest2 = new com.announcements.AutomateAnnouncements.dtos.request.AssetRequestDTO();
        assetRequest2.setOwner(ownerId);
        assetRequest2.setType("video");
        assetRequest2.setSource("generated.mp4");
        assetRequest2.setBlobUrl(videoUrl);
        AssetResponseDTO asset = assetService.create(assetRequest2);
        log.info("Asset created with ID: {}", asset.getId());

        // Create post draft (legacy)
        com.announcements.AutomateAnnouncements.dtos.request.PostDraftRequestDTO postDraftRequest2 = new com.announcements.AutomateAnnouncements.dtos.request.PostDraftRequestDTO();
        postDraftRequest2.setTitle(title);
        postDraftRequest2.setDescription(description);
        postDraftRequest2.setAssetId(asset.getId());
        postDraftRequest2.setTargets(targets);
        postDraftRequest2.setStatus("pending");
        PostDraftResponseDTO postDraft = postDraftService.create(postDraftRequest2);
        log.info("Post draft created with ID: {}", postDraft.getId());

        // Create UserPost (new system)
        UserProfile userProfile = userProfileRepository.findById(ownerId)
                .orElseThrow(() -> new RuntimeException("User profile not found with ID: " + ownerId));

        UserPostRequestDTO userPostRequest = new UserPostRequestDTO();
        userPostRequest.setTitle(title);
        userPostRequest.setContent(description);
        userPostRequest.setVideoUrl(videoUrl);
        userPostRequest.setStatus("published"); // Auto-publish generated videos

        // Parse targets into list
        List<String> targetList = Arrays.stream(targets.split(","))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .collect(Collectors.toList());
        userPostRequest.setTargetPlatforms(targetList);

        UserPostResponseDTO userPost = userPostService.createPost(userProfile.getAuthUserId(), userPostRequest);
        log.info("UserPost created with ID: {}", userPost.getId());

        // Send to n8n
        n8nIntegrationService.sendVideoToN8n(title, description, videoUrl, postDraft.getTargets());
        log.info("Generated video data sent to n8n successfully");

        return videoUrl;
    }
}